apiVersion: "v1"
name: "cloudevent-diary"
description: ""
version: "0.1.0"
appVersion: "0.1.0"
type: application
home: "http://github.com/ozabalaferrera/cloudevent_diary"
sources:
- "http://github.com/ozabalaferrera/cloudevent_diary"
keywords:
- "knative"
- "cloudevent"
maintainers:
- name: "ozabalaferrera"
  url: "http://github.com/ozabalaferrera"
